/* Generated by eXtremeDB Schema Compiler, build 279
 * at Thu May 12 19:44:43 2005
 */

#include "kgtsdb.h"
#include "mcowrap.h"


/*---------------------------------------------------------------------*/
/* dictionary                                                          */

mco_dictionary_h kgtsdb_get_dictionary(void)
{ 
  static mco_dictionary_t  dict; 
  static int dictionary_ready = 0; 

  if( ! dictionary_ready ) 
  {
    static mco_dict_field_t v_field_info[65] = { 
    /* CHANNEL_B */
    {"block", {1, 1, 10, 1, 1, 10}, 1, 0, 0, -1, 1, 0, 0},
    {"id_channel_b", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"id_e1", {2, 2, 4, 2, 2, 4}, 2, 0, 0, -1, 2, 0, 0},
    {"nki", {1, 1, 11, 1, 1, 11}, 1, 0, 0, -1, 1, 0, 0},
    {"tid", {2, 2, 8, 2, 2, 8}, 2, 0, 0, -1, 2, 0, 0},
    {"userid", {2, 2, 6, 2, 2, 6}, 2, 0, 0, -1, 2, 0, 0},
    /* CHANNEL_D */
    {"call_pointers", {4, 2, 12, 6, 4, 12}, 1, 1, 0, -1, 1, 0, 0},
    {"id_channel_d", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"id_e1", {2, 2, 16, 2, 2, 18}, 2, 0, 0, -1, 2, 0, 0},
    {"last_call_pointer", {4, 4, 8, 4, 4, 8}, 3, 0, 0, -1, 4, 0, 0},
    {"max_call_pointer", {4, 4, 4, 4, 4, 4}, 3, 0, 0, -1, 4, 0, 0},
    /* CH_B_D */
    {"id_channel_b", {4, 4, 4, 4, 4, 4}, 3, 0, 0, -1, 4, 0, 0},
    {"id_channel_d", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"numb_b", {2, 2, 8, 2, 2, 8}, 2, 0, 0, -1, 2, 0, 0},
    /* CH_B_TRUNK_GR */
    {"id_channel_b", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"id_trunk_gr", {1, 1, 4, 1, 1, 4}, 1, 0, 0, -1, 1, 0, 0},
    /* DESTINATION */
    {"id_destination", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"name", {20, 1, 4, 20, 1, 4}, 7, 0, 0, -1, 20, 0, 0},
    /* DIRECTION */
    {"id_direction", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"lpr", {1, 1, 5, 1, 1, 5}, 1, 0, 0, -1, 1, 0, 0},
    {"name", {20, 1, 6, 20, 1, 6}, 7, 0, 0, -1, 20, 0, 0},
    {"to_amts", {1, 1, 4, 1, 1, 4}, 1, 0, 0, -1, 1, 0, 0},
    /* DIRECTION_DESTINATION */
    {"id_destination", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"id_direction", {4, 4, 8, 4, 4, 8}, 3, 0, 0, -1, 4, 0, 0},
    {"points", {4, 4, 4, 4, 4, 4}, 3, 0, 0, -1, 4, 0, 0},
    /* E1 */
    {"avrcs", {1, 1, 6, 1, 1, 6}, 1, 0, 0, -1, 1, 0, 0},
    {"avrre", {1, 1, 9, 1, 1, 9}, 1, 0, 0, -1, 1, 0, 0},
    {"avrscs", {1, 1, 5, 1, 1, 5}, 1, 0, 0, -1, 1, 0, 0},
    {"hdb3", {1, 1, 4, 1, 1, 4}, 1, 0, 0, -1, 1, 0, 0},
    {"hierror", {1, 1, 11, 1, 1, 11}, 1, 0, 0, -1, 1, 0, 0},
    {"id_e1", {2, 2, 0, 2, 2, 0}, 2, 0, 0, -1, 2, 0, 0},
    {"id_ie1", {1, 1, 13, 1, 1, 13}, 1, 0, 0, -1, 1, 0, 0},
    {"number", {1, 1, 2, 1, 1, 2}, 1, 0, 0, -1, 1, 0, 0},
    {"offscsre", {1, 1, 10, 1, 1, 10}, 1, 0, 0, -1, 1, 0, 0},
    {"sia", {1, 1, 3, 1, 1, 3}, 1, 0, 0, -1, 1, 0, 0},
    {"sia16", {1, 1, 8, 1, 1, 8}, 1, 0, 0, -1, 1, 0, 0},
    {"slip", {1, 1, 12, 1, 1, 12}, 1, 0, 0, -1, 1, 0, 0},
    {"ss7", {1, 1, 7, 1, 1, 7}, 1, 0, 0, -1, 1, 0, 0},
    /* IE1 */
    {"altera", {1, 1, 6, 1, 1, 6}, 1, 0, 0, -1, 1, 0, 0},
    {"cmatr", {1, 1, 5, 1, 1, 5}, 1, 0, 0, -1, 1, 0, 0},
    {"dsp_fifo", {1, 1, 4, 1, 1, 4}, 1, 0, 0, -1, 1, 0, 0},
    {"exist", {1, 1, 2, 1, 1, 2}, 1, 0, 0, -1, 1, 0, 0},
    {"id_ie1", {1, 1, 8, 1, 1, 8}, 1, 0, 0, -1, 1, 0, 0},
    {"id_upo", {1, 1, 0, 1, 1, 0}, 1, 0, 0, -1, 1, 0, 0},
    {"liu_framers", {1, 1, 7, 1, 1, 7}, 1, 0, 0, -1, 1, 0, 0},
    {"number", {1, 1, 1, 1, 1, 1}, 1, 0, 0, -1, 1, 0, 0},
    {"ram", {1, 1, 3, 1, 1, 3}, 1, 0, 0, -1, 1, 0, 0},
    /* TRUNK_GROUP */
    {"b_total", {4, 4, 44, 4, 4, 44}, 3, 0, 0, -1, 4, 0, 0},
    {"b_used", {4, 4, 4, 4, 4, 4}, 3, 0, 0, -1, 4, 0, 0},
    {"cng_hi_limit", {8, 4, 28, 8, 4, 28}, 11, 0, 0, -1, 8, 0, 0},
    {"cng_low_limit", {8, 4, 36, 8, 4, 36}, 11, 0, 0, -1, 8, 0, 0},
    {"first_channel_b_id", {4, 4, 12, 4, 4, 12}, 3, 0, 0, -1, 4, 0, 0},
    {"id_direction", {4, 4, 8, 4, 4, 8}, 3, 0, 0, -1, 4, 0, 0},
    {"id_extern_set", {4, 4, 24, 4, 4, 24}, 3, 0, 0, -1, 4, 0, 0},
    {"id_region_set", {4, 4, 20, 4, 4, 20}, 3, 0, 0, -1, 4, 0, 0},
    {"id_trunk_group", {1, 1, 52, 1, 1, 52}, 1, 0, 0, -1, 1, 0, 0},
    {"inout", {1, 1, 49, 1, 1, 49}, 1, 0, 0, -1, 1, 0, 0},
    {"isdn", {1, 1, 50, 1, 1, 50}, 1, 0, 0, -1, 1, 0, 0},
    {"last_occupied_channel_b", {4, 4, 16, 4, 4, 16}, 3, 0, 0, -1, 4, 0, 0},
    {"max_channel_b_id", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, 0, 0},
    {"overuse", {1, 1, 48, 1, 1, 48}, 1, 0, 0, -1, 1, 0, 0},
    {"slzsl", {1, 1, 51, 1, 1, 51}, 1, 0, 0, -1, 1, 0, 0},
    /* UPO */
    {"exist", {1, 1, 1, 1, 1, 1}, 1, 0, 0, -1, 1, 0, 0},
    {"id_upo", {1, 1, 2, 1, 1, 2}, 1, 0, 0, -1, 1, 0, 0},
    {"number", {1, 1, 0, 1, 1, 0}, 1, 0, 0, -1, 1, 0, 0}
    };

    static mco_dict_struct_t v_struct_info[11] = { 
    { "CHANNEL_B", 0, 6, (v_field_info + 0), 12, 4, 12, 4 },
    { "CHANNEL_D", 1, 5, (v_field_info + 6), 18, 4, 20, 4 },
    { "CH_B_D", 0, 3, (v_field_info + 11), 10, 4, 10, 4 },
    { "CH_B_TRUNK_GR", 0, 2, (v_field_info + 14), 5, 4, 5, 4 },
    { "DESTINATION", 0, 2, (v_field_info + 16), 24, 4, 24, 4 },
    { "DIRECTION", 0, 4, (v_field_info + 18), 26, 4, 26, 4 },
    { "DIRECTION_DESTINATION", 0, 3, (v_field_info + 22), 12, 4, 12, 4 },
    { "E1", 0, 13, (v_field_info + 25), 14, 2, 14, 2 },
    { "IE1", 0, 9, (v_field_info + 38), 9, 1, 9, 1 },
    { "TRUNK_GROUP", 0, 15, (v_field_info + 47), 53, 4, 53, 4 },
    { "UPO", 0, 3, (v_field_info + 62), 3, 1, 3, 1 }
    };

    dictionary_ready = 1;
    dict.str_class_names = 0;
    dict.str_index_names = 0;
    {
      static  mco_dict_class_info_t class_inf[12] = { 
        { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, 
        { 0, 3, -1, -1, 12, 0, -1, 0, 0, 0, 0, 152, (v_struct_info + 0), 12, 0, 0 }  /* CHANNEL_B */ , 
        { 4, 6, -1, -1, 0, 0, -1, 0, 0, -1, -2, 8, (v_struct_info + 1), 18, 0, 0 }  /* CHANNEL_D */ , 
        { 7, 10, -1, -1, 10, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 2), 10, 0, 0 }  /* CH_B_D */ , 
        { 11, 12, -1, -1, 5, 0, -1, 0, 0, 1, 1, 152, (v_struct_info + 3), 5, 0, 0 }  /* CH_B_TRUNK_GR */ , 
        { 13, 14, -1, -1, 24, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 4), 24, 0, 0 }  /* DESTINATION */ , 
        { 15, 15, -1, -1, 26, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 5), 26, 0, 0 }  /* DIRECTION */ , 
        { 16, 18, -1, -1, 12, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 6), 12, 0, 0 }  /* DIRECTION_DESTINATION */ , 
        { 19, 22, -1, -1, 14, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 7), 14, 0, 0 }  /* E1 */ , 
        { 23, 26, -1, -1, 9, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 8), 9, 0, 0 }  /* IE1 */ , 
        { 27, 29, -1, -1, 53, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 9), 53, 0, 0 }  /* TRUNK_GROUP */ , 
        { 30, 32, -1, -1, 3, 0, -1, 0, 0, -1, -2, 24, (v_struct_info + 10), 3, 0, 0 }  /* UPO */ 
      };
      dict.v_class_info = class_inf;
    }

    { static mco_dict_event_t mco_v_evdsc[2] = { 
        {1, 4, 8, 2, 2, 0 },
        {4, 4, 0, 4, 3, 0 }
      };
      dict.v_desc_events = & mco_v_evdsc[0];
    }


    dict.v_all_struct = v_struct_info;
    {
      static mco_dict_index_field_t v_all_index_fields[ 41] = {
          { 4, -1, 2, 2, 0 } /* [0] */
        , { 11, -1, 1, 1, 0 } /* [1] */
        , { 0, -1, 4, 3, 0 } /* [2] */
        , { 8, -1, 2, 2, 0 } /* [3] */
        , { 4, -1, 2, 2, 0 } /* [4] */
        , { 0, -1, 4, 3, 0 } /* [5] */
        , { 0, -1, 4, 3, 0 } /* [6] */
        , { 16, -1, 2, 2, 0 } /* [7] */
        , { 0, -1, 4, 3, 0 } /* [8] */
        , { 0, -1, 4, 3, 0 } /* [9] */
        , { 4, -1, 4, 3, 0 } /* [10] */
        , { 4, -1, 4, 3, 0 } /* [11] */
        , { 8, -1, 2, 2, 0 } /* [12] */
        , { 0, -1, 4, 3, 0 } /* [13] */
        , { 8, -1, 2, 2, 0 } /* [14] */
        , { 4, -1, 1, 1, 0 } /* [15] */
        , { 0, -1, 4, 3, 0 } /* [16] */
        , { 0, -1, 4, 3, 0 } /* [17] */
        , { 0, -1, 4, 3, 0 } /* [18] */
        , { 0, -1, 4, 3, 0 } /* [19] */
        , { 0, -1, 4, 3, 0 } /* [20] */
        , { 8, -1, 4, 3, 0 } /* [21] */
        , { 0, -1, 4, 3, 0 } /* [22] */
        , { 8, -1, 4, 3, 0 } /* [23] */
        , { 0, -1, 4, 3, 0 } /* [24] */
        , { 13, -1, 1, 1, 0 } /* [25] */
        , { 2, -1, 1, 1, 0 } /* [26] */
        , { 2, -1, 1, 1, 0 } /* [27] */
        , { 13, -1, 1, 1, 0 } /* [28] */
        , { 0, -1, 2, 2, 0 } /* [29] */
        , { 0, -1, 1, 1, 0 } /* [30] */
        , { 1, -1, 1, 1, 0 } /* [31] */
        , { 1, -1, 1, 1, 0 } /* [32] */
        , { 0, -1, 1, 1, 0 } /* [33] */
        , { 8, -1, 1, 1, 0 } /* [34] */
        , { 52, -1, 1, 1, 0 } /* [35] */
        , { 52, -1, 1, 1, 0 } /* [36] */
        , { 8, -1, 4, 3, 0 } /* [37] */
        , { 2, -1, 1, 1, 0 } /* [38] */
        , { 0, -1, 1, 1, 0 } /* [39] */
        , { 2, -1, 1, 1, 0 } /* [40] */
      }; 

      static mco_dict_index_t v_all_indexes_info[ 33] = {
          { 1, 2, -1, 2051, & v_all_index_fields[0], 0 } /* CHANNEL_B.by_id_ie1_nki [0] */
        , { 1, 2, -1, 2051, & v_all_index_fields[2], 0 } /* CHANNEL_B.by_id_channel_b_tid [1] */
        , { 1, 1, -1, 2049, & v_all_index_fields[4], 0 } /* CHANNEL_B.by_id_e1 [2] */
        , { 1, 1, -1, 2050, & v_all_index_fields[5], 33000 } /* CHANNEL_B.by_id_channel_b_hash [3] */
        , { 2, 1, -1, 2049, & v_all_index_fields[6], 0 } /* CHANNEL_D.by_id_channel_d [4] */
        , { 2, 1, -1, 2049, & v_all_index_fields[7], 0 } /* CHANNEL_D.by_id_e1 [5] */
        , { 2, 1, -1, 2050, & v_all_index_fields[8], 33000 } /* CHANNEL_D.by_channel_d_hash [6] */
        , { 3, 1, -1, 2049, & v_all_index_fields[9], 0 } /* CH_B_D.by_id_chanel_d [7] */
        , { 3, 1, -1, 2049, & v_all_index_fields[10], 0 } /* CH_B_D.by_id_chanel_b [8] */
        , { 3, 2, -1, 2051, & v_all_index_fields[11], 0 } /* CH_B_D.by_id_chanel_b_numb_b [9] */
        , { 3, 2, -1, 2051, & v_all_index_fields[13], 0 } /* CH_B_D.by_id_chanel_d_numb_b [10] */
        , { 4, 2, -1, 2049, & v_all_index_fields[15], 0 } /* CH_B_TRUNK_GR.by_id_trunk_gr_id_channel_b [11] */
        , { 4, 1, -1, 2050, & v_all_index_fields[17], 33000 } /* CH_B_TRUNK_GR.by_id_channel_b [12] */
        , { 5, 1, -1, 2050, & v_all_index_fields[18], 10 } /* DESTINATION.by_id_destination_hash [13] */
        , { 5, 1, -1, 2049, & v_all_index_fields[19], 0 } /* DESTINATION.by_id_destination [14] */
        , { 6, 1, -1, 2050, & v_all_index_fields[20], 10 } /* DIRECTION.by_id_direction_hash [15] */
        , { 7, 1, -1, 2049, & v_all_index_fields[21], 0 } /* DIRECTION_DESTINATION.by_id_direction [16] */
        , { 7, 1, -1, 2049, & v_all_index_fields[22], 0 } /* DIRECTION_DESTINATION.by_id_destination [17] */
        , { 7, 2, -1, 2049, & v_all_index_fields[23], 0 } /* DIRECTION_DESTINATION.by_id_direction_and_id_destination [18] */
        , { 8, 2, -1, 2051, & v_all_index_fields[25], 0 } /* E1.by_id_ie1_number [19] */
        , { 8, 1, -1, 2049, & v_all_index_fields[27], 0 } /* E1.by_number [20] */
        , { 8, 1, -1, 2049, & v_all_index_fields[28], 0 } /* E1.by_id_ie1 [21] */
        , { 8, 1, -1, 2050, & v_all_index_fields[29], 1000 } /* E1.by_id_e1 [22] */
        , { 9, 2, -1, 2051, & v_all_index_fields[30], 0 } /* IE1.by_id_upo_number [23] */
        , { 9, 1, -1, 2049, & v_all_index_fields[32], 0 } /* IE1.by_number [24] */
        , { 9, 1, -1, 2049, & v_all_index_fields[33], 0 } /* IE1.by_id_upo [25] */
        , { 9, 1, -1, 2050, & v_all_index_fields[34], 100 } /* IE1.by_id_ie1 [26] */
        , { 10, 1, -1, 2050, & v_all_index_fields[35], 10 } /* TRUNK_GROUP.by_id_trunk_group_hash [27] */
        , { 10, 1, -1, 2049, & v_all_index_fields[36], 0 } /* TRUNK_GROUP.by_id_trunk_group [28] */
        , { 10, 1, -1, 2049, & v_all_index_fields[37], 0 } /* TRUNK_GROUP.by_direction [29] */
        , { 11, 1, -1, 2049, & v_all_index_fields[38], 0 } /* UPO.by_id_upo [30] */
        , { 11, 1, -1, 2050, & v_all_index_fields[39], 10 } /* UPO.by_number_hash [31] */
        , { 11, 1, -1, 2050, & v_all_index_fields[40], 10 } /* UPO.by_id_upo_hash [32] */
      }; 

      dict.v_desc_indexes = v_all_indexes_info;
    }

    dict.version_major             = 2;
    dict.version_minor             = 3;
    dict.version_build             = 279;
    dict.reserved                  = 0;
    dict.oid_is_supported          = 0;
    dict.auto_oid_supported        = 0;
    dict.n_class_codes             = 11;
    dict.n_list_indexes            = 0;
    dict.n_autoid_indexes          = 0;
    dict.n_history_indexes         = 0;
    dict.n_desc_indexes            = 33;
    dict.n_desc_events             = 2;
    dict.n_structs                 = 11;
    dict.num_oid_estimation        = 0;
    dict.num_HA_estimation         = 0;
    dict.max_numof_indexes_per_obj = 4;
    dict.exact_OID_sizeof          = 0;
    dict.layout_OID_size           = 0;
  }

  return &dict; 
}

